### ISSUE TITLE
[Install] Python version in the Installation Guide

### ISSUE THREAD

**Issue by isdanni** [NREL/G2Aero#2]
For `python setup.py install` in the [Installation](https://github.com/NREL/G2Aero#installation) of README.md, if the user running the command using Python 2.x version, they will see the error `TypeError: 'encoding' is an invalid keyword argument for this function`, which is caused by using `open(...)` function in the code. I'd suggest one of the following:

1. Change the code from `open(...)` to:
```python
import io
io.open(...)
```
io works in both 2.x and 3.x python versions.
 
2.  Specify in the [README.md](https://github.com/NREL/G2Aero/blob/main/README.md) that install the package using Python3.x.

**Comment by olgadoronina** [comment]
@ isdanni thanks for catching this, I added Python version requirement to the installation guide, see commit [f14b4df](https://github.com/NREL/G2Aero/commit/f14b4dfdef4cdd5266dc2caf7704758d943bba40)

**Comment by isdanni** [comment]
> 

Thanks!

linking https://github.com/openjournals/joss-reviews/issues/5408 for tracking review progress.
