### ISSUE TITLE
[Doc] Missing Function Explanation in API Doc

### ISSUE THREAD

**Issue by isdanni** [NREL/G2Aero#4]
Following functions seem to be missing explanation in the API doc:

- [Grassmann.check_orthogonality](https://g2aero.readthedocs.io/en/latest/technical_reference/Grassmann.html#Grassmann.check_orthogonality)
- [SPD.tangent_space](https://g2aero.readthedocs.io/en/latest/technical_reference/SPD.html#SPD.tangent_space)
- [reparametrization.cst_matrix](https://g2aero.readthedocs.io/en/latest/technical_reference/reparametrization.html#reparametrization.cst_matrix)
- [reparametrization.cst_reparametrization](https://g2aero.readthedocs.io/en/latest/technical_reference/reparametrization.html#reparametrization.cst_reparametrization)
- [reparametrization.curvature_planar](https://g2aero.readthedocs.io/en/latest/technical_reference/reparametrization.html#reparametrization.curvature_planar)
- [transform.global_blade_coordinates](https://g2aero.readthedocs.io/en/latest/technical_reference/transform.html#transform.global_blade_coordinates)
- [module-geometry_gmsh](https://g2aero.readthedocs.io/en/latest/technical_reference/geometry_gmsh.html#module-geometry_gmsh)
- [utils.add_tailedge_gap](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.add_tailedge_gap)
- [utils.arc_distance](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.arc_distance)
- [utils.calc_curvature](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.calc_curvature)
- [utils.position_airfoil](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.position_airfoil)
- [utils.remove_tailedge_gap](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.remove_tailedge_gap)
- [utils.tailedge_gap](https://g2aero.readthedocs.io/en/latest/technical_reference/utils.html#utils.tailedge_gap)

**Comment by olgadoronina** [comment]
@isdanni, Thanks for catching missing function explanations in API docs. I added all missing descriptions in  [f14b4df](https://github.com/NREL/G2Aero/commit/f14b4dfdef4cdd5266dc2caf7704758d943bba40) commit

**Comment by isdanni** [comment]
linking https://github.com/openjournals/joss-reviews/issues/5408 for tracking review progress.
